spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: kazan
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoices:
  database: memory